version: "3.1"
services:
    redis:
      image: redis:alpine
      container_name: nftmarketplacemain-redis
      ports:
        - "6380:6379"

    mysql:
      platform: linux/x86_64
      image: mysql:8.0
      container_name: nftmarketplacemain-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=20207a63f0901ea878fc
        - MYSQL_DATABASE=nft_marketplace_main
        - MYSQL_USER=nft_user
        - MYSQL_PASSWORD=nft@2022
      ports:
        - "3307:3306"

    php:
      build: ./
      container_name: nftmarketplacemain-php
      links:
        - mysql:mysql
      ports:
        - "9001:9000"
      volumes:
        - .:/application
        - ./:/var/www/html
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    webserver:
      image: nginx:1.18
      container_name: nftmarketplacemain-webserver
      working_dir: /application
      links:
        - php:fpm
      volumes:
        - .:/application
        - ./:/var/www/html
        - ./storage/logs/nginx/:/var/log/nginx
        - ./docker/nginx_conf:/etc/nginx/conf.d/
      ports:
       - "80:80"
